name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run prepublish 
      - name: Publish
        run: npm publish